"""Add card and image_uri models

Revision ID: 03f6719045b7
Revises: d4867f3a4c0a
Create Date: 2022-08-17 06:51:15.210675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03f6719045b7'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('oracle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('mtgo_id', sa.Integer(), nullable=True),
    sa.Column('mtgo_foil_id', sa.Integer(), nullable=True),
    sa.Column('tcgplayer_id', sa.Integer(), nullable=True),
    sa.Column('cardmarket_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('foil', sa.Boolean(), nullable=True),
    sa.Column('nonfoil', sa.Boolean(), nullable=True),
    sa.Column('set_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('set_shortname', sa.String(), nullable=True),
    sa.Column('set_name', sa.String(), nullable=True),
    sa.Column('rarity', sa.Enum('common', 'uncommon', 'rare', 'mythic', name='rarity'), nullable=True),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_id'), 'card', ['id'], unique=False)
    op.create_index(op.f('ix_card_lang'), 'card', ['lang'], unique=False)
    op.create_index(op.f('ix_card_name'), 'card', ['name'], unique=False)
    op.create_index(op.f('ix_card_oracle_id'), 'card', ['oracle_id'], unique=False)
    op.create_table('imageuri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('small', sa.String(), nullable=True),
    sa.Column('normal', sa.String(), nullable=True),
    sa.Column('large', sa.String(), nullable=True),
    sa.Column('png', sa.String(), nullable=True),
    sa.Column('art_crop', sa.String(), nullable=True),
    sa.Column('border_crop', sa.String(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imageuri_id'), 'imageuri', ['id'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_imageuri_id'), table_name='imageuri')
    op.drop_table('imageuri')
    op.drop_index(op.f('ix_card_oracle_id'), table_name='card')
    op.drop_index(op.f('ix_card_name'), table_name='card')
    op.drop_index(op.f('ix_card_lang'), table_name='card')
    op.drop_index(op.f('ix_card_id'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
