"""Add Scout object

Revision ID: 16e9f8f155f5
Revises: b2248a279f86
Create Date: 2022-08-20 23:27:57.975927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e9f8f155f5'
down_revision = 'b2248a279f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scout_type', sa.Enum('common', 'uncommon', 'rare', 'mythic', name='scouttype'), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('foil', sa.Boolean(), nullable=True),
    sa.Column('nonfoil', sa.Boolean(), nullable=True),
    sa.Column('first_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scout_id'), 'scout', ['id'], unique=False)
    op.create_index(op.f('ix_scout_price'), 'scout', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scout_price'), table_name='scout')
    op.drop_index(op.f('ix_scout_id'), table_name='scout')
    op.drop_table('scout')
    # ### end Alembic commands ###
