"""Change scouttype to string

Revision ID: 355ec2d4aaa3
Revises: 5b4ea59579f9
Create Date: 2022-08-22 07:35:30.279512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '355ec2d4aaa3'
down_revision = '5b4ea59579f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scout', 'scout_type',
               existing_type=postgresql.ENUM('common', 'uncommon', 'rare', 'mythic', name='scouttype'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scout', 'scout_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('common', 'uncommon', 'rare', 'mythic', name='scouttype'),
               existing_nullable=True)
    # ### end Alembic commands ###
