"""Update ScoutType Enum

Revision ID: 3adbd1055494
Revises: 16e9f8f155f5
Create Date: 2022-08-20 23:48:16.795576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adbd1055494'
down_revision = '16e9f8f155f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
