"""Re-add scouttype

Revision ID: 5b4ea59579f9
Revises: e43479efbaa9
Create Date: 2022-08-22 07:01:07.619399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4ea59579f9'
down_revision = 'e43479efbaa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scout', sa.Column('scout_type', sa.Enum('price', 'quantity', 'buylist', name='scouttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scout', 'scout_type')
    # ### end Alembic commands ###
