"""Change price from float to decimal

Revision ID: b2248a279f86
Revises: f19471e1e32d
Create Date: 2022-08-20 20:51:25.595976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2248a279f86'
down_revision = 'f19471e1e32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cardprice', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cardprice', 'price',
               existing_type=sa.DECIMAL(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
