"""Add CardPrice and add relationships to Card and Store

Revision ID: f19471e1e32d
Revises: 48fff0337c7e
Create Date: 2022-08-20 20:08:42.055368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19471e1e32d'
down_revision = '48fff0337c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('is_foil', sa.Boolean(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardprice_id'), 'cardprice', ['id'], unique=False)
    op.create_index(op.f('ix_cardprice_price'), 'cardprice', ['price'], unique=False)
    op.create_index(op.f('ix_cardprice_quantity'), 'cardprice', ['quantity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cardprice_quantity'), table_name='cardprice')
    op.drop_index(op.f('ix_cardprice_price'), table_name='cardprice')
    op.drop_index(op.f('ix_cardprice_id'), table_name='cardprice')
    op.drop_table('cardprice')
    # ### end Alembic commands ###
